// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Checkout: typeof import('./src/components/shoppingCart/checkout/index.vue')['default']
    CheckoutProducts: typeof import('./src/components/shoppingCart/checkout/checkoutProducts.vue')['default']
    ElImage: typeof import('element-plus/es')['ElImage']
    HelperBar: typeof import('./src/components/common/helperBar.vue')['default']
    PriceQuantityTray: typeof import('./src/components/products/product/priceQuantityTray.vue')['default']
    Product: typeof import('./src/components/products/product/index.vue')['default']
    ProductSearchItem: typeof import('./src/components/products/productSearchItem.vue')['default']
    ProductsList: typeof import('./src/components/productsList.vue')['default']
    ProductsSearchList: typeof import('./src/components/products/productsSearchList.vue')['default']
    Quantity: typeof import('./src/components/common/quantity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingAddress: typeof import('./src/components/shoppingCart/checkout/shippingAddress.vue')['default']
    ShippingAddressForm: typeof import('./src/components/shoppingCart/checkout/shippingAddressForm.vue')['default']
    ShoppingCart: typeof import('./src/components/shoppingCart/index.vue')['default']
    ShoppingCartItem: typeof import('./src/components/shoppingCart/shoppingCartItem.vue')['default']
    ShoppingCartList: typeof import('./src/components/shoppingCart/shoppingCartList.vue')['default']
    SubTotalPriceTray: typeof import('./src/components/shoppingCart/subTotalPriceTray.vue')['default']
  }
}
