// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Checkout: typeof import('./src/components/checkout/index.vue')['default']
    CheckoutBuyNowTray: typeof import('./src/components/checkout/checkoutBuyNowTray.vue')['default']
    CheckOutProduct: typeof import('./src/components/checkout/checkOutProduct.vue')['default']
    CheckOutProductsList: typeof import('./src/components/checkout/checkOutProductsList.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelperBar: typeof import('./src/components/common/helperBar.vue')['default']
    PriceQuantityTray: typeof import('./src/components/products/product/priceQuantityTray.vue')['default']
    Product: typeof import('./src/components/products/product/index.vue')['default']
    ProductSearchItem: typeof import('./src/components/products/productSearchItem.vue')['default']
    ProductsSearchList: typeof import('./src/components/products/productsSearchList.vue')['default']
    Quantity: typeof import('./src/components/common/quantity.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShippingAddress: typeof import('./src/components/checkout/shippingAddress.vue')['default']
    ShippingAddressForm: typeof import('./src/components/checkout/shippingAddressForm.vue')['default']
    ShoppingCartItem: typeof import('./src/components/shoppingCart/shoppingCartItem.vue')['default']
    ShoppingCartList: typeof import('./src/components/shoppingCart/shoppingCartList.vue')['default']
    SubTotalPriceTray: typeof import('./src/components/shoppingCart/subTotalPriceTray.vue')['default']
    YoureNotLoggedIn: typeof import('./src/components/checkout/youreNotLoggedIn.vue')['default']
  }
}
